### ISSUE TITLE
Перегруппировать компоненты Storybook`а

### ISSUE THREAD

**Issue by maximzadorkin** [quarx-ui/quarx#107]

**Comment by aak-lear** [comment]
- [ ] Изменить файловую структуру репозитория:
```
core/src/
    main/*
    system/*
```
- [ ] Изменить файловую структуру сторибука:

![telegram-cloud-photo-size-2-5465608199743848821-x](https://user-images.githubusercontent.com/54769688/203100714-7958c6bb-9d88-4851-8850-c9d1ec9260af.jpg)
