### ISSUE TITLE
Реализовать Popper&Popover компонент

### ISSUE THREAD

**Issue by maximzadorkin** [quarx-ui/quarx#38]
**Требования**
- [x] 12 позиций относительно якоря
- [x] Позиционирование с заданными координатами
- [ ] Применение скруглений
- [x] Обработка clickAway
- [x] Включение / отключение Backdrop
- [x] Рендер с Portal и без

**Comment by aak-lear** [comment]
**Требования**
- [ ] Позиционирование: 12 позиций относительно якоря + абсолютное
- [ ] Применение скруглений
- [ ] Обработка clickAway
- [ ] Включение / отключение Backdrop
- [ ] Рендер с Portal и без

**Comment by aak-lear** [comment]
пункты 1 и 2 реализованы в #65
